### ISSUE TITLE
Entering flashing mode

### ISSUE THREAD

**Issue by PlaneStuffRC** [crycode-de/mcp-can-boot#3]
From what what i can see, i have to reset the mcu manually in order to enter flashing mode, is there any option to do this from the app ?

**Comment by crycode-de** [comment]
You can use the watchdog to reset the MCU by your main application.

To do so, you have to disable all interrupts, setup the watchdog for a very short time and enter an infinite loop like this:
```c
#include <avr/wdt.h>

cli(); // disable interrupts
wdt_enable(WDTO_15MS); // watchdog timeout 15ms
while(1); // wait for watchdog to reset mcu
```

This will reset your mcu and enter the bootloader.

In the flash-app you may use the `-R` or `--reset` argument to send a CAN message which triggers the code above to do reset.
